"""empty message

Revision ID: 17e4b3d7cad2
Revises: 
Create Date: 2022-11-02 18:20:03.192423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17e4b3d7cad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constituent', sa.Column('constituent_external_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constituent', 'constituent_external_id')
    # ### end Alembic commands ###
